hr:
  username: team.hr@hello.io
  password: vr8yvnzl
  master: s6~Axc
tech:
  username: team.tech@hello.io
  password: xKMNZEjH
  master: s6~Axc
developers:
  username: team.developers@hello.io
  password: vr8yvnzl
  master: s6~Axc
designers:
  username: team.designers@hello.io
  password: R3JZATJS
  master: s6~Axc
marketing:
  username: team.marketing@hello.io
  password: WEVfBLCS
  master: s6~Axc
managers:
  username: team.managers@hello.io
  password: wW8MrDH1
  master: s6~Axc
buh:
  username: team.buh@hello.io
  password: AA523RJ0
  master: s6~Axc
office:
  username: team.office@hello.io
  password: dItzelKJ
  master: s6~Axc
sapozhnikova:
  username: d.sapozhnikova@hello.io
  password: ohNmRqw6
  master: s6~Axc
dyubarov:
  username: e.dyubarov@hello.io
  password: tWPnUZx8
  master: s6~Axc
korchagina:
  username: e.korchagina@hello.io
  password: 5DloPQgH
  master: s6~Axc
admin:
  username: admin@hello.io
  password: d00J@EJb
  master: Sayid20sir20ah!
test:
  username: test@hello.io
  password: sosatt
  master: jops
