srek:
  credentials:
    username: bulba@hello.io
    password: kskskkskks
    master: srek
  users:
    - srek@test.io
    - s.rek@test.io
    - sr.ek@test.io
office:
  credentials:
    username: ocel@ocel.ru
    password: ls,njjd!
    master: ocel
  users:
    - ocel@ocel.ru
