developers:
  credentials:
    username: team.developers@hello.io
    password: vr8yvnzl
    master: s6~Axc
  users:
    - a.manvelian@hello.io
    - a.ilyukhin@hello.io
    - a.kasatkina@hello.io
    - a.molodtsov@hello.io
    - a.filipenkov@hello.io
    - v.tuleneva@hello.io
    - m.grigoriev@hello.io
    - d.mikolaichuk@hello.io
    - d.terentyev@hello.io
    - k.mikolaichuk@hello.io
    - m.ruf@hello.io
    - m.bondin@hello.io
    - o.korabenkov@hello.io
    - o.chernenko@hello.io
    - y.panaev@hello.io
    - n.sokolov@hello.io
    - g.bychenok@hello.io
    - v.tuleneva@hello.io
    - a.sadykov@hello.io
    - a.frolov@hello.io
designers:
  credentials:
    username: team.designers@hello.io
    password: R3JZATJS
    master: s6~Axc
  users:
    - a.zhigalov@hello.io
    - a.glinskiy@hello.io
    - a.bekisheva@hello.io
    - a.atnoguzin@hello.io
    - d.chekov@hello.io
    - v.matkovsky@hello.io
    - d.maximov@hello.io
    - d.komarov@hello.io
    - i.pudov@hello.io
    - i.kondrashov@hello.io
    - m.nefedov@hello.io
    - mk@hello.io
    - m.koval@hello.io
    - n.kaur@hello.io
    - r.savinov@hello.io
    - t.chepasheva@hello.io
    - s.prihodko@hello.io
    - t.samarakovskaya@hello.io
    - j.artamonova@hello.io
    - m.rube@hello.io
    - m.korotkina@hello.io
finance:
  credentials:
    username: team.buh@hello.io
    password: AA523RJ0
    master: s6~Axc
  users:
    - e.nikolayeva@hello.io
    - ot@hello.io
    - a.kaloeva@hello.io
tech:
  credentials:
    username: team.tech@hello.io
    password: xKMNZEjH
    master: s6~Axc
  users:
    - support.team@hello.io
    - a.bystrov@hello.io
    - g.abdurazakov@hello.io
    - e.krivenkin@hello.io
    - iko@hello.io
    - i.kondratiev@hello.io
    - n.brovchenko@hello.io
    - n.berezhnoy@hello.io
    - a.urlapov@hello.io
marketing:
  credentials:
    username: team.marketing@hello.io
    password: WEVfBLCS
    master: s6~Axc
  users:
    - a.chernov@hello.io
    - a.zavyalov@hello.io
    - a.abramov@hello.io
    - d.stepanenko@hello.io
    - i.volkov@hello.io
    - e.rossiyskaya@hello.io
    - l.kovalev@hello.io
    - n.skibenko@hello.io
    - p.merkureva@hello.io
    - r.rodionov@hello.io
    - s.shumov@hello.io
manager:
  credentials:
    username: team.mamager@hello.io
    password: wW8MrDH1
    master: s6~Axc
  users:
    - v.palamarchuk@hello.io
    - v.zuev@hello.io
    - d.kolyvanova@hello.io
    - i.mordachev@hello.io
    - i.chefranov@hello.io
    - e.kochanovskiy@hello.io
admin:
  credentials:
    username: admin@hello.io
    password: d00J@EJb
    master: Sayid20sir20ah!
  users:
    - a.chichko@hello.io
    - maxim@hello.io
    - a.palamarchuk@hello.io
office:
  credentials:
    username: team.office@hello.io
    password: dItzelKJ
    master: s6~Axc
  users:
    - n.muravieva@hello.io
hr:
  credentials:
    username: team.hr@hello.io
    password: vr8yvnzl
    master: s6~Axc
  users:
    - a.egorova@hello.io
test:
  credentials:
    username: test@hello.io
    password: sosatt
    master: jops
  users:
    - polina28113@mail.ru
    - sasha.che007@gmail.com
sapozhnikova:
  credentials:
    username: d.sapozhnikova@hello.io
    password: ohNmRqw6
    master: s6~Axc
  users:
    - d.sapozhnikova@hello.io
dyubarov:
  credentials:
    username: e.dyubarov@hello.io
    password: tWPnUZx8
    master: s6~Axc
  users:
    - e.dyubarov@hello.io
korchagina:
  credentials:
    username: e.korchagina@hello.io
    password: 5DloPQgH
    master: s6~Axc
  users:
    - e.korchagina@hello.io
