developers:
  - a.manvelian@hello.io
  - a.ilyukhin@hello.io
  - a.kasatkina@hello.io
  - a.molodtsov@hello.io
  - a.filipenkov@hello.io
  - v.tuleneva@hello.io
  - m.grigoriev@hello.io
  - d.mikolaichuk@hello.io
  - d.terentyev@hello.io
  - k.mikolaichuk@hello.io
  - m.ruf@hello.io
  - m.bondin@hello.io
  - o.korabenkov@hello.io
  - o.chernenko@hello.io
designers:
  - a.zhigalov@hello.io
  - a.glinskiy@hello.io
  - a.bekisheva@hello.io
  - a.atnoguzin@hello.io
  - d.chekov@hello.io
  - v.matkovsky@hello.io
  - d.maximov@hello.io
  - d.komarov@hello.io
  - i.pudov@hello.io
  - i.kondrashov@hello.io
  - m.nefedov@hello.io
  - mk@hello.io
  - m.koval@hello.io
  - n.kaur@hello.io
  - r.savinov@hello.io
  - t.chepasheva@hello.io
  - s.prihodko@hello.io
  - t.samarakovskaya@hello.io
  - j.artamonova@hello.io
finance:
  - e.nikolayeva@hello.io
  - ot@hello.io
tech:
  - support.team@hello.io
  - a.bystrov@hello.io
  - g.abdurazakov@hello.io
  - e.krivenkin@hello.io
  - iko@hello.io
  - i.kondratiev@hello.io
  - n.brovchenko@hello.io
  - n.berezhnoy@hello.io
marketing:
  - a.chernov@hello.io
  - a.zavyalov@hello.io
  - a.abramov@hello.io
  - d.stepanenko@hello.io
  - i.volkov@hello.io
  - e.rossiyskaya@hello.io
  - l.kovalev@hello.io
  - n.skibenko@hello.io
  - p.merkureva@hello.io
  - r.rodionov@hello.io
  - s.shumov@hello.io
manager:
  - v.palamarchuk@hello.io
  - v.zuev@hello.io
  - d.kolyvanova@hello.io
  - i.mordachev@hello.io
  - i.chefranov@hello.io
  - e.kochanovskiy@hello.io
admin:
  - a.chichko@hello.io
  - maxim@hello.io
  - a.palamarchuk@hello.io
office:
  - n.muravieva@hello.io
hr:
  - test@hello.io
test:
  - polina28113@mail.ru
  - sasha.che007@gmail.com
sapozhnikova: d.sapozhnikova@hello.io
dyubarov: e.dyubarov@hello.io
korchagina: e.korchagina@hello.io
